#!/bin/bash

cmake_dir=
if [ $# == 0 ]; then
	cmake_dir=release
	mkdir -p $cmake_dir
	cd $cmake_dir
	cmake \
		-DCMAKE_BUILD_TYPE=Release \
		-DMODE_UDPTALK=OFF \
		-DMODE_UART=OFF \
		\
		..
elif [ $1 == "debug" ]; then
	cmake_dir=debug
	mkdir -p $cmake_dir
	cd $cmake_dir
	cmake \
		-DCMAKE_BUILD_TYPE=Debug \
		-DMODE_UCPAAS=OFF \
		-DMODE_UART=OFF \
		-DAUTO_SLEEP=OFF \
		-DMODE_FACE=OFF \
		..
elif [ $1 == "x86" ]; then
	cmake_dir=x86
	mkdir -p $cmake_dir
	cd $cmake_dir
	cmake \
		-DCMAKE_BUILD_TYPE=Debug \
		-DPLATFORM_RV1108=OFF \
		-DMODE_UDPTALK=OFF \
		-DMODE_VIDEO=OFF \
		-DMODE_FACE=OFF \
		-DMODE_UCPAAS=OFF \
		..
fi
make
if [ $? == 0 ]; then
	cd ..
	if [[ $# == 0 || $1 == "debug" ]]; then
		if [ $# == 0 ]; then
			$RV1108_CROOS_PATH/bin/arm-linux-strip $cmake_dir/cat_eye
			cp $cmake_dir/cat_eye ../burn/root_usr/
			cp $cmake_dir/cat_eye $RV1108_SDK_PATH/common/overlay/usr/
			cp $cmake_dir/cat_eye update/root/usr

			$RV1108_CROOS_PATH/bin/arm-linux-strip $cmake_dir/cammer_video
			cp $cmake_dir/cammer_video ../burn/userdata
			cp $cmake_dir/cammer_video $RV1108_SDK_PATH/common/userdata/

			$RV1108_CROOS_PATH/bin/arm-linux-strip $cmake_dir/cammer_cap
			cp $cmake_dir/cammer_cap ../burn/userdata
			cp $cmake_dir/cammer_cap $RV1108_SDK_PATH/common/userdata/

			$RV1108_CROOS_PATH/bin/arm-linux-strip $cmake_dir/singlechip
			cp $cmake_dir/singlechip ../burn/userdata
			cp $cmake_dir/singlechip $RV1108_SDK_PATH/common/userdata/
		fi
		cp $cmake_dir/cat_eye ~/arm_share/cat_eye/
		cp $cmake_dir/singlechip ~/arm_share/cat_eye/
		cp $cmake_dir/cammer_video ~/arm_share/cat_eye/
		tar czf Update.tar.gz update/
		mv Update.tar.gz $cmake_dir/update.cab
	fi
fi

